#enumerate - keeps counts of iterations
file = open('pro.fasta','r')
for n, line in enumerate(file):
    print(n)     # gives the counts of lines
    print(line)  # prints each line
    
'''
output
0
>sp|P02533|K1C14_HUMAN Keratin, type I cytoskeletal 14 OS=Homo sapiens OX=9606 GN=KRT14 PE=1 SV=4

1
MTTCSRQFTSSSSMKGSCGIGGGIGGGSSRISSVLAGGSCRAPSTYGGGLSVSSSRFSSG

2
GACGLGGGYGGGFSSSSSSFGSGFGGGYGGGLGAGLGGGFGGGFAGGDGLLVGSEKVTMQ

3
NLNDRLASYLDKVRALEEANADLEVKIRDWYQRQRPAEIKDYSPYFKTIEDLRNKILTAT

4
VDNANVLLQIDNARLAADDFRTKYETELNLRMSVEADINGLRRVLDELTLARADLEMQIE

5
SLKEELAYLKKNHEEEMNALRGQVGGDVNVEMDAAPGVDLSRILNEMRDQYEKMAEKNRK

6
DAEEWFFTKTEELNREVATNSELVQSGKSEISELRRTMQNLEIELQSQLSMKASLENSLE

7
ETKGRYCMQLAQIQEMIGSVEEQLAQLRCEMEQQNQEYKILLDVKTRLEQEIATYRRLLE

8
GEDAHLSSSQFSSGSQSSRDVTSSSRQIRTKVMDVHDGKVVSTHEQVLRTKN

9
>sp|Q8N1A0|KT222_HUMAN Keratin-like protein KRT222 OS=Homo sapiens OX=9606 GN=KRT222 PE=1 SV=1

10
MELSQLLNEIRANYEKILTRNQIETVLSTRIQLEEDISKKMDKDEEALKAAQAELKEARR

11
QWHHLQVEIESLHAVERGLENSLHASEQHYQMQLQDLETVIEGLEKELQEVRRGIEKQLQ

12
EHEMLLNTKMRLEQEIATYRHLLEKEEIRYYGCIQGGKKDKKPTTSRVGFVLPSAIINEI

13
SFTTKVPQKYENENVETVTKQAILNGSIVKESTEAHGTIQTEKVDEVIKEWEGSFFKDNP

14
RLRKKSVSLRFDLHLAATDEGCLETKQDNLPDIEVRLIMRRSCSIPSIKPPSTAN

15
>sp|P78385|KRT83_HUMAN Keratin, type II cuticular Hb3 OS=Homo sapiens OX=9606 GN=KRT83 PE=1 SV=2

16
MTCGFNSIGCGFRPGNFSCVSACGPRPSRCCITAAPYRGISCYRGLTGGFGSHSVCGGFR

17
AGSCGRSFGYRSGGVCGPSPPCITTVSVNESLLTPLNLEIDPNAQCVKQEEKEQIKSLNS

18
RFAAFIDKVRFLEQQNKLLETKLQFYQNRECCQSNLEPLFAGYIETLRREAECVEADSGR

19
LASELNHVQEVLEGYKKKYEEEVALRATAENEFVALKKDVDCAYLRKSDLEANVEALIQE

20
IDFLRRLYEEEIRILQSHISDTSVVVKLDNSRDLNMDCIVAEIKAQYDDIATRSRAEAES

21
WYRSKCEEMKATVIRHGETLRRTKEEINELNRMIQRLTAEVENAKCQNSKLEAAVAQSEQ

22
QGEAALSDARCKLAELEGALQKAKQDMACLIREYQEVMNSKLGLDIEIATYRRLLEGEEQ

23
RLCEGVEAVNVCVSSSRGGVVCGDLCVSGSRPVTGSVCSAPCNGNLVVSTGLCKPCGQLN

24
TTCGGGSCGQGRH

25
>sp|P78386|KRT85_HUMAN Keratin, type II cuticular Hb5 OS=Homo sapiens OX=9606 GN=KRT85 PE=1 SV=1

26
MSCRSYRISSGCGVTRNFSSCSAVAPKTGNRCCISAAPYRGVSCYRGLTGFGSRSLCNLG

27
SCGPRIAVGGFRAGSCGRSFGYRSGGVCGPSPPCITTVSVNESLLTPLNLEIDPNAQCVK

28
QEEKEQIKSLNSRFAAFIDKVRFLEQQNKLLETKWQFYQNQRCCESNLEPLFSGYIETLR

29
REAECVEADSGRLASELNHVQEVLEGYKKKYEEEVALRATAENEFVVLKKDVDCAYLRKS

30
DLEANVEALVEESSFLRRLYEEEIRVLQAHISDTSVIVKMDNSRDLNMDCIIAEIKAQYD

31
DVASRSRAEAESWYRSKCEEMKATVIRHGETLRRTKEEINELNRMIQRLTAEIENAKCQR

32
AKLEAAVAEAEQQGEAALSDARCKLAELEGALQKAKQDMACLLKEYQEVMNSKLGLDIEI

33
ATYRRLLEGEEHRLCEGVGSVNVCVSSSRGGVSCGGLSYSTTPGRQITSGPSAIGGSITV

34
VAPDSCAPCQPRSSSFSCGSSRSVRFA

35
>sp|O43790|KRT86_HUMAN Keratin, type II cuticular Hb6 OS=Homo sapiens OX=9606 GN=KRT86 PE=1 SV=1

36
MTCGSYCGGRAFSCISACGPRPGRCCITAAPYRGISCYRGLTGGFGSHSVCGGFRAGSCG

37
RSFGYRSGGVCGPSPPCITTVSVNESLLTPLNLEIDPNAQCVKQEEKEQIKSLNSRFAAF

38
IDKVRFLEQQNKLLETKLQFYQNRECCQSNLEPLFEGYIETLRREAECVEADSGRLASEL

39
NHVQEVLEGYKKKYEEEVSLRATAENEFVALKKDVDCAYLRKSDLEANVEALIQEIDFLR

40
RLYEEEIRVLQSHISDTSVVVKLDNSRDLNMDCIIAEIKAQYDDIVTRSRAEAESWYRSK

41
CEEMKATVIRHGETLRRTKEEINELNRMIQRLTAEVENAKCQNSKLEAAVAQSEQQGEAA

42
LSDARCKLAELEGALQKAKQDMACLIREYQEVMNSKLGLDIEIATYRRLLEGEEQRLCEG

43
VGSVNVCVSSSRGGVVCGDLCASTTAPVVSTRVSSVPSNSNVVVGTTNACAPSARVGVCG

44
GSCKRC
'''